"""LaTeX validation and auto-fix package.

This package provides LaTeX structure validation and automatic error correction
for beamer presentations generated by paperdeck.
"""

from .backup_manager import BackupManager, BackupMetadata
from .cli_integration import (
    get_validation_summary,
    report_validation_results,
    validate_and_fix_latex_file,
    validate_latex_file,
)
from .delimiter_types import DelimiterType
from .environment_matcher import EnvironmentMatcher
from .error_types import ErrorType
from .fix_confidence import FixConfidence
from .latex_fixer import FixerConfig, LaTeXFixer
from .latex_validator import LaTeXValidator, ValidationConfig
from .utils import is_escaped, strip_comments
from .validation_errors import FixChange, ValidationError, ValidationResult

__all__ = [
    'BackupManager',
    'BackupMetadata',
    'DelimiterType',
    'EnvironmentMatcher',
    'ErrorType',
    'FixChange',
    'FixConfidence',
    'FixerConfig',
    'LaTeXFixer',
    'LaTeXValidator',
    'ValidationConfig',
    'ValidationError',
    'ValidationResult',
    'get_validation_summary',
    'is_escaped',
    'report_validation_results',
    'strip_comments',
    'validate_and_fix_latex_file',
    'validate_latex_file',
]
