"""LaTeX validation and auto-fix package.

This package provides LaTeX structure validation and automatic error correction
for beamer presentations generated by paperdeck.
"""

from .latex_validator import LaTeXValidator, ValidationConfig
from .validation_errors import ValidationError, ValidationResult, FixChange
from .environment_matcher import EnvironmentMatcher
from .latex_fixer import LaTeXFixer, FixerConfig

__all__ = [
    'LaTeXValidator',
    'ValidationConfig',
    'ValidationError',
    'ValidationResult',
    'FixChange',
    'EnvironmentMatcher',
    'LaTeXFixer',
    'FixerConfig',
]
